kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
  namespace: jenkins
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete